//DELAYING THE CODE FROM EXECUTING UNTIL ALL DOM ASSETS HAVE BEEN LOADED

$(document).ready(function () {

    //CHANGING THE OPACITY OF '.navLogo' ON HOVER

    //FADING THE UNDERLINE OF 'header ul li a' ON HOVER

    //'header ul li a' SMOOTH SCROLLING TO CORRESPONDING SECTION ON CLICK

    //'.arrowDown' SMOOTH SCROLLING TO INTRODUCTION ON CLICK

    //'.arrowUp' SMOOTH SCROLLING TO TOP ON CLICK

    //ANIMATE '.rightArrow' AND '.leftArrow' ARROWS ON HOVER

    //HIGHLIGHTING THE '.socialMedia' ICONS ON HOVER

});
