//DELAYING THE CODE FROM EXECUTING UNTIL ALL DOM ASSETS HAVE BEEN LOADED

$(document).ready(function () {

    //CHANGING THE OPACITY OF .navLogo ON HOVER

    //FADING THE UNDERLINE OF header ul li a ON HOVER

    //SMOOTH SCROLLING TO INTRODUCTION ON CLICK .arrowDown

    //SMOOTH SCROLLING TO TOP ON CLICK .arrowUp

    //'BOUNCE'/'POINT' .rightArrow AND .leftArrow ARROWS ON HOVER

    //'BOUNCE'/'POINT' .rightArrow AND .leftArrow ARROWS ON HOVER

});
